// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "be.doeraene" % "scalajs-jquery_sjs0.6_2.11" % "0.9.1",
  "com.beachape" % "enumeratum-circe_sjs0.6_2.11" % "1.5.14",
  "com.beachape" % "enumeratum-macros_2.11" % "1.5.9",
  "com.beachape" % "enumeratum_sjs0.6_2.11" % "1.5.12",
  "com.chuusai" % "shapeless_sjs0.6_2.11" % "2.3.2",
  "com.github.mpilquist" % "simulacrum_sjs0.6_2.11" % "0.10.0",
  "com.lihaoyi" % "scalatags_sjs0.6_2.11" % "0.6.5",
  "com.lihaoyi" % "sourcecode_sjs0.6_2.11" % "0.1.3",
  "com.sksamuel.scapegoat" % "scalac-scapegoat-plugin_2.11" % "1.3.0",
  "io.circe" % "circe-core_sjs0.6_2.11" % "0.8.0",
  "io.circe" % "circe-generic-extras_sjs0.6_2.11" % "0.8.0",
  "io.circe" % "circe-generic_sjs0.6_2.11" % "0.8.0",
  "io.circe" % "circe-numbers_sjs0.6_2.11" % "0.8.0",
  "io.circe" % "circe-parser_sjs0.6_2.11" % "0.8.0",
  "io.circe" % "circe-scalajs_sjs0.6_2.11" % "0.8.0",
  "org.scala-js" % "scalajs-dom_sjs0.6_2.11" % "0.9.1",
  "org.scala-js" % "scalajs-library_2.11" % "0.6.16",
  "org.scala-lang.modules" % "scala-xml_2.11" % "1.0.5",
  "org.typelevel" % "cats-core_sjs0.6_2.11" % "0.9.0",
  "org.typelevel" % "cats-kernel_sjs0.6_2.11" % "0.9.0",
  "org.typelevel" % "cats-macros_sjs0.6_2.11" % "0.9.0",
  "org.typelevel" % "machinist_sjs0.6_2.11" % "0.6.1",
  "org.typelevel" % "macro-compat_2.11" % "1.1.1",
  "org.typelevel" % "macro-compat_sjs0.6_2.11" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH a3925498fde6471fe3d6f22a862708cb20427d3c
