// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.beachape" % "enumeratum-circe_2.11" % "1.5.14",
  "com.beachape" % "enumeratum-macros_2.11" % "1.5.9",
  "com.beachape" % "enumeratum_2.11" % "1.5.12",
  "com.chuusai" % "shapeless_2.11" % "2.3.2",
  "com.github.mpilquist" % "simulacrum_2.11" % "0.10.0",
  "com.sksamuel.scapegoat" % "scalac-scapegoat-plugin_2.11" % "1.3.0",
  "io.circe" % "circe-core_2.11" % "0.8.0",
  "io.circe" % "circe-generic-extras_2.11" % "0.8.0",
  "io.circe" % "circe-generic_2.11" % "0.8.0",
  "io.circe" % "circe-jawn_2.11" % "0.8.0",
  "io.circe" % "circe-numbers_2.11" % "0.8.0",
  "io.circe" % "circe-parser_2.11" % "0.8.0",
  "org.scala-lang.modules" % "scala-xml_2.11" % "1.0.5",
  "org.spire-math" % "jawn-parser_2.11" % "0.10.4",
  "org.typelevel" % "cats-core_2.11" % "0.9.0",
  "org.typelevel" % "cats-kernel_2.11" % "0.9.0",
  "org.typelevel" % "cats-macros_2.11" % "0.9.0",
  "org.typelevel" % "machinist_2.11" % "0.6.1",
  "org.typelevel" % "macro-compat_2.11" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH 66badbe5f8d33762b1b846239958d2806ad45d14
